# ecommerce_platform/.gitlab-ci.yml

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker-compose build

test:
  stage: test
  script:
    - docker-compose up -d
    - docker-compose run products pytest tests/test_products.py
    - docker-compose down

deploy:
  stage: deploy
  script:
    - docker-compose up -d
  only:
    - main
