# ecommerce_platform/docker-compose.yml

version: '3.9'

services:
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts/init_products_db.sh:/docker-entrypoint-initdb.d/init_products_db.sh
      - ./scripts/init_cart_db.sh:/docker-entrypoint-initdb.d/init_cart_db.sh
      - ./scripts/init_orders_db.sh:/docker-entrypoint-initdb.d/init_orders_db.sh
      - ./scripts/init_payments_db.sh:/docker-entrypoint-initdb.d/init_payments_db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  products:
    build:
      context: .
      dockerfile: products/Dockerfile
    container_name: products_service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:12345@db/products_db
    depends_on:
      db:
        condition: service_healthy

  cart:
    build:
      context: .
      dockerfile: cart/Dockerfile
    container_name: cart_service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:12345@db/cart_db
    depends_on:
      db:
        condition: service_healthy

  orders:
    build:
      context: .
      dockerfile: orders/Dockerfile
    container_name: orders_service
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://postgres:12345@db/orders_db
    depends_on:
      db:
        condition: service_healthy

  payments:
    build:
      context: ./payments
      dockerfile: Dockerfile
    container_name: payments_service
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=postgresql://postgres:12345@db/payments_db
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_service
    ports:
      - "80:80"
    depends_on:
      - products
      - cart
      - orders
      - payments

  main_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: main_app
    ports:
      - "8004:8004"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
