version: '3.8'

services:
  products:
    build:
      context: .
      dockerfile: products/Dockerfile
    container_name: products_service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:12345@db/products_db
    depends_on:
      - db

  cart:
    build:
      context: .
      dockerfile: cart/Dockerfile
    container_name: cart_service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:12345@db/cart_db
    depends_on:
      - db

  orders:
    build:
      context: .
      dockerfile: orders/Dockerfile
    container_name: orders_service
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://postgres:12345@db/orders_db
    depends_on:
      - db

  payments:
    build:
      context: ./payments
      dockerfile: Dockerfile
    container_name: payments_service
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=postgresql://postgres:12345@db/payments_db
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: products_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
